from __future__ import annotations

from typing import Protocol


class DocumentStorage(Protocol):
    provider_name: str

    def save(self, key: str, content: bytes) -> None: ...
    def read(self, key: str) -> bytes: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...
    def get_size(self, key: str) -> int: ...
